# Gradle Properties
org.gradle.jvmargs=-Xmx2G
#org.gradle.configuration-cache=true
org.gradle.caching=true
mod_id=boxtrot
maven_group_id=dev.cammiescorner.boxtrot
mod_display_name=The Box Trot
mod_description=Bringing the best feature from the 22w13oneblockatatime April Fools snapshot to regular MC!
sources_url=https://github.com/CammiesCorner/The-Box-Trot
issues_url=https://github.com/CammiesCorner/The-Box-Trot/issues
license_url=https://github.com/CammiesCorner/The-Box-Trot/blob/HEAD/LICENSE.md
discord_url=https://cammiescorner.dev/discord
homepage_url=https://cammiescorner.dev
