[versions]
fabric_loom = "1.10.1"

minecraft = "1.21.1"
fabric_loader = "0.16.13"

# https://parchmentmc.org/docs/getting-started
parchment_minecraft = "1.21.1"
parchment_mappings = "2024.11.17"

jetbrains_annotations = "26.0.1"
fabric_api = "0.115.4+1.21.1"
modmenu = "11.0.3"
resourceful_config = "3.0.10"
pehkui = "3.8.3"
common_network = "1.0.17-beta.2-1.21.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
resourceful_config = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.21", version.ref = "resourceful_config" }
common_network_fabric = { module = "mysticdrew:common-networking-fabric", version.ref = "common_network" }
pehkui = { module = "com.github.Virtuoel:Pehkui", version.ref = "pehkui" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
